services:
  app:
    # image: vladvysth/hexlet-1:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: make test